// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getDesktopStorage } from '@/lib/desktopBridge';

const DEFAULT_SUPABASE_URL = 'https://awkvzbpnihtgceqdwisc.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_czq_XwvIyrAeg1lXbuh7pQ_XjfeonmL';

// Keep production connection stable even when external env providers are inconsistent.
const SUPABASE_URL = DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = DEFAULT_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY (ou VITE_SUPABASE_ANON_KEY) nao configurada.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getDesktopStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
